#!/bin/bash -e
if [ $# -ne 4 ]
then
  echo "$0 <input.csv> <p_min> <p_max> {absolute|relative}" >&2
  exit 1
fi
APP_DIR=$(dirname "$(readlink -e "$0")")

DATA=$("$APP_DIR/selector" "$1" "$2" "$3")

# plot each name
NAMES=$(awk '{ print $1 }' <<<"$DATA")
for name in $NAMES
do
  timeout 2 "$APP_DIR/plot_name" "$1" "$name" "$4" || true
done

# display data
echo
echo
sort -k 4 -n <<< "$DATA"
