#!/bin/bash -e

if [ $# -lt 3 ]
then
  echo "$0 <input.csv> {absolute|relative} <name1> [<name2> ... <nameN>]" >&2
  exit 1
fi

FILE=$1
shift
OYAXIS=$1
shift

DATA_DIR=$(mktemp -d)

case "$OYAXIS" in
  "absolute")
    COUNT_MAX=$(awk -F ',' '{ print $3 }' "$FILE" | sort -n | tail -1)
    OYRANGE="set yrange [0:$COUNT_MAX]"
  ;;
  "relative")
    OYRANGE=""
  ;;
  *)
    "$0" --help
  ;;
esac


echo "$PLOTS"

gnuplot -p <<EOF
set title '$OYAXIS name comparison plot'
set xlabel 'year'
set ylabel 'birth count'
$OYRANGE

plot \\
$(
FIRST=true
for name in "$@"
do
  grep "^$name," "$FILE" | awk -F ',' '{ print $2, $3 }' | sort -n > "$DATA_DIR/${name}.dat"
  if ! $FIRST
  then
    echo ", \\"
  fi
  FIRST=false
  echo -n "$NEWLINE '$DATA_DIR/${name}.dat' using 1:2 title '$name' smooth csplines lw 3"
done
)
EOF

rm -rf "$DATA_DIR"
