#!/bin/bash -e

if [ $# -ne 3 ]
then
  echo "$0 <input.csv> <name> {absolute|relative}" >&2
  exit 1
fi

FILE=$1
shift
NAME=$1
shift
OYAXIS=$1
shift

DATA=$(mktemp)

case "$OYAXIS" in
  "absolute")
    COUNT_MAX=$(awk -F ',' '{ print $3 }' "$FILE" | sort -n | tail -1)
    OYRANGE="set yrange [0:$COUNT_MAX]"
  ;;
  "relative")
    OYRANGE=""
  ;;
  *)
    "$0" --help
  ;;
esac

grep "^$NAME," "$FILE" | awk -F ',' '{ print $2, $3 }' | sort -n > "$DATA"
gnuplot -p <<EOF
set title '$NAME - $OYAXIS name plot'
set xlabel 'year'
set ylabel 'birth count'
$OYRANGE

plot \
  "$DATA" using 1:2 title 'data points' ps 3, \
  "$DATA" using 1:2 title 'trend' smooth csplines lw 3
EOF

rm -f "$DATA"
