#!/usr/bin/env python
import sys

# command line help and paramters
if len(sys.argv) != 1+3:
    sys.stderr.write(sys.argv[0] + " <input.csv> <p_min> <p_max>\n")
    sys.stderr.write("probabilities are ginve in percent (i.e. '2.5' means 2.5%)\n")
    sys.exit(1)
inputFilePath = sys.argv[1]
minProb = float(sys.argv[2])
maxProb = float(sys.argv[3])

# read input data
data = []
with open(inputFilePath) as f:
    for line in f.readlines():
        tab = line.rstrip().split(',')
        entry = [ tab[0], int(tab[1]), int(tab[2]) ]
        data.append(entry)

# add probabilities for a given name, per year
years = []
for e in data:
    years.append(e[1])
years = set(years)

# compute sum of all names, per year
yearSum = {}
for e in data:
    year = e[1]
    count = e[2]
    if year in yearSum:
        yearSum[year] += count
    else:
        yearSum[year] = count

# add percentage probability on a given name, per year
for e in data:
    e.append( e[2]/float(yearSum[e[1]])*100 )

# compute per-name statistics
stats = {}
for e in data:
    name = e[0]
    p = e[3]
    if name in stats:
        stats[name].append(p)
    else:
        stats[name] = [p]

# sort probabilities for each year, to keep some, common ordering
for k,v in stats.items():
    v.sort()

# print results, matching required criteria
for k,v in stats.items():
    avg = sum(v) / float(len(v))
    med = v[ len(v)/2 ]
    if minProb <= med and med <= maxProb:
        print( k + "  ->  median  " + str(med) + "  average  " + str(avg) ) #+ "  data =  " + str(v) )
