#!/usr/bin/env python
import sys

stats = {}

for path in sys.argv[1:]:
    with open(path) as f:
        for line in f.readlines():
            data = line.rstrip().split(' ')
            k = data[0]
            v = float(data[2])
            if data[0] in stats:
                stats[k].append(v)
            else:
                stats[k] = [v]

for k,v in stats.items():
    v.sort()


for k,v in stats.items():
    print(k + " -> " + str(v) )
    if v[0] > v[-1]:
        print("DUPA!")
        sys.exit(42)
